//@prepros-append vendors/jquery.mask.min.js
//@prepros-append vendors/jquery.fancybox.min.js
//@prepros-append vendors/device.min.js
//@prepros-append vendors/waypoints.js
//@prepros-append vendors/swiper.min.js
//@prepros-append vendors/jquery.star-rating-svg.min.js
//@prepros-append vendors/popper.min.js
//@prepros-append vendors/tippy.min.js
//@prepros-append vendors/jquery.event.move.js
//@prepros-append vendors/jquery.twentytwenty.js
//@prepros-append vendors/imagesloaded.pkgd.min.js